# Generated by Django 4.0.5 on 2022-06-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0002_home_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='about',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='certificados',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='home',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interesses_hobbies',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='interesses_hobbies',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='interesses_hobbies',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='texto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='subtitulo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=20),
        ),
    ]
