# Generated by Django 4.0.5 on 2022-06-02 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_licenciatura_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='texto',
            field=models.CharField(max_length=200000000),
        ),
    ]
