# Generated by Django 4.0.5 on 2022-06-05 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('portfolio', '0003_alter_about_texto_alter_about_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatura',
            name='image',
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='texto2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='texto',
            field=models.TextField(),
        ),
    ]
