# Generated by Django 4.0.5 on 2022-06-02 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_licenciatura_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(null=True, upload_to='image')),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.CharField(max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='home',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='home',
            name='texto',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='home',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='projetos',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
