# Generated by Django 4.0.5 on 2022-06-05 14:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_licenciatura_image_licenciatura_texto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='texto3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='texto4',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='subtitulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
