# Generated by Django 4.0.5 on 2022-06-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_licenciatura_texto3_licenciatura_texto4_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Licenciatura',
        ),
    ]
