# Generated by Django 4.0.5 on 2022-06-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_delete_licenciatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=200)),
                ('ect', models.CharField(max_length=200)),
            ],
        ),
    ]
