# Generated by Django 4.0.5 on 2022-06-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_licenciatura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='ect',
            field=models.IntegerField(default=5),
        ),
    ]
