# Generated by Django 4.0.5 on 2022-06-05 21:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_alter_licenciatura_ect'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacao',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
