# Generated by Django 4.0.5 on 2022-06-03 21:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_web_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web',
            name='url',
        ),
        migrations.AddField(
            model_name='home_web',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
