# Generated by Django 4.0.5 on 2022-06-05 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_about_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='texto',
            field=models.CharField(max_length=50),
        ),
    ]
