# Generated by Django 4.0.5 on 2022-06-05 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_home_home_projets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outras_habilitacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=20)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.CharField(max_length=200)),
            ],
        ),
    ]
