# Generated by Django 4.0.5 on 2022-06-05 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_outras_habilitacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licenciatura_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=200)),
                ('ect', models.IntegerField(default=5)),
            ],
        ),
        migrations.CreateModel(
            name='Licenciatura_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.CharField(max_length=200)),
                ('semestre', models.CharField(max_length=200)),
                ('ect', models.IntegerField(default=5)),
            ],
        ),
        migrations.RenameModel(
            old_name='Licenciatura',
            new_name='Licenciatura_1',
        ),
    ]
