# Generated by Django 4.0.5 on 2022-06-05 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_licenciatura_2_licenciatura_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educacao',
            name='url',
        ),
        migrations.AddField(
            model_name='educacao',
            name='logo',
            field=models.ImageField(null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='educacao',
            name='texto',
            field=models.TextField(max_length=20000),
        ),
    ]
