# Generated by Django 4.0.5 on 2022-06-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_remove_educacao_url_educacao_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacao',
            name='texto',
            field=models.TextField(max_length=200),
        ),
    ]
