# Generated by Django 4.0.5 on 2022-06-05 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0016_alter_educacao_texto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Licenciatura_2',
        ),
        migrations.DeleteModel(
            name='Licenciatura_3',
        ),
    ]
