# Generated by Django 4.0.5 on 2022-06-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_delete_licenciatura_2_delete_licenciatura_3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Licenciatura_1',
            new_name='Licenciatura',
        ),
    ]
