# Generated by Django 4.0.5 on 2022-06-06 00:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_rename_ano_licenciatura_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='disciplina',
            field=models.CharField(max_length=120),
        ),
    ]
