# Generated by Django 4.0.5 on 2022-06-06 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_licenciatura_link_alter_licenciatura_disciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatura',
            name='link',
        ),
    ]
