# Generated by Django 4.0.5 on 2022-06-06 01:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_licenciatura_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
