# Generated by Django 4.0.5 on 2022-06-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0023_alter_certificados_texto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=20000)),
            ],
        ),
        migrations.AlterField(
            model_name='outras_habilitacoes',
            name='texto',
            field=models.TextField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='outras_habilitacoes',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
