# Generated by Django 4.0.5 on 2022-06-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_web_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutSystems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(max_length=20)),
                ('texto', models.TextField(max_length=20000)),
            ],
        ),
    ]
