# Generated by Django 4.0.5 on 2022-06-06 02:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0027_outsystems_texto2_alter_outsystems_subtitulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='outsystems',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
