# Generated by Django 4.0.5 on 2022-06-06 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0028_outsystems_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratorio',
            name='texto',
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='disciplina',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='link',
            field=models.URLField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
    ]
