# Generated by Django 4.0.5 on 2022-06-06 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_laboratorio_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projetos',
            name='url',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projetos',
            name='texto',
            field=models.TextField(max_length=20000),
        ),
    ]
